
open "https://www.dropbox.com/"
open "https://www.google.com/chrome"
open "http://www.sublimetext.com/3"
open "http://www.videolan.org/"
open "http://www.alfredapp.com/"
open "http://www.sequelpro.com/"
open "https://slack.com/"
open "https://www.spotify.com/"
open "http://www.sourcetreeapp.com/"
open "http://blog.boastr.net/" #bettertouchtool
open "http://www.libreoffice.org/download"
open "https://www.transmissionbt.com/download/"
open "http://zipzapmac.com/go2shell"
open "http://evernote.com/skitch/"
open "https://justgetflux.com/"
open "https://popcorntime.io/"
open "https://www.mozilla.org/thunderbird/"
open "https://www.mozilla.org/firefox/"
#open "http://25.io/mou/"
open "http://www.skype.com/download-skype/skype-for-computer/"
open "https://developer.apple.com/xcode/downloads/"
open "https://imageoptim.com/"
open "http://appducate.com/2013/09/batch-resize-images-automator-script/"
open "https://agilebits.com/downloads"
open "http://iterm2.com/"
open "https://github.com/altercation/solarized/tree/master/iterm2-colors-solarized"

#open -a Go2Shell --args config
